# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lecteur_video.ui',
# licensing of 'lecteur_video.ui' applies.
#
# Created: Thu Jul 18 17:35:49 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1066, 806)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ecran = QVideoWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ecran.sizePolicy().hasHeightForWidth())
        self.ecran.setSizePolicy(sizePolicy)
        self.ecran.setObjectName("ecran")
        self.verticalLayout.addWidget(self.ecran)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, 5, 10, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.debut = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debut.setFont(font)
        self.debut.setObjectName("debut")
        self.horizontalLayout_2.addWidget(self.debut)
        self.timeline = QtWidgets.QSlider(self.centralwidget)
        self.timeline.setMinimumSize(QtCore.QSize(5, 40))
        self.timeline.setOrientation(QtCore.Qt.Horizontal)
        self.timeline.setObjectName("timeline")
        self.horizontalLayout_2.addWidget(self.timeline)
        self.fin = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fin.setFont(font)
        self.fin.setObjectName("fin")
        self.horizontalLayout_2.addWidget(self.fin)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(30)
        self.horizontalLayout.setContentsMargins(-1, 20, -1, 20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pblecture = QtWidgets.QPushButton(self.centralwidget)
        self.pblecture.setObjectName("pblecture")
        self.horizontalLayout.addWidget(self.pblecture)
        self.pbpause = QtWidgets.QPushButton(self.centralwidget)
        self.pbpause.setObjectName("pbpause")
        self.horizontalLayout.addWidget(self.pbpause)
        self.pbstop = QtWidgets.QPushButton(self.centralwidget)
        self.pbstop.setMinimumSize(QtCore.QSize(0, 20))
        self.pbstop.setObjectName("pbstop")
        self.horizontalLayout.addWidget(self.pbstop)
        self.pbsuivant = QtWidgets.QPushButton(self.centralwidget)
        self.pbsuivant.setObjectName("pbsuivant")
        self.horizontalLayout.addWidget(self.pbsuivant)
        self.pbprecedent = QtWidgets.QPushButton(self.centralwidget)
        self.pbprecedent.setObjectName("pbprecedent")
        self.horizontalLayout.addWidget(self.pbprecedent)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        spacerItem = QtWidgets.QSpacerItem(10, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_3.addWidget(self.listWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pbplus = QtWidgets.QPushButton(self.centralwidget)
        self.pbplus.setObjectName("pbplus")
        self.horizontalLayout_3.addWidget(self.pbplus)
        self.pbmoins = QtWidgets.QPushButton(self.centralwidget)
        self.pbmoins.setObjectName("pbmoins")
        self.horizontalLayout_3.addWidget(self.pbmoins)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.dialVolume = QtWidgets.QDial(self.centralwidget)
        self.dialVolume.setMaximumSize(QtCore.QSize(80, 80))
        self.dialVolume.setMaximum(100)
        self.dialVolume.setObjectName("dialVolume")
        self.horizontalLayout_4.addWidget(self.dialVolume)
        self.labelVol = QtWidgets.QLabel(self.centralwidget)
        self.labelVol.setObjectName("labelVol")
        self.horizontalLayout_4.addWidget(self.labelVol)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1066, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.debut.setText(QtWidgets.QApplication.translate("MainWindow", "Début", None, -1))
        self.fin.setText(QtWidgets.QApplication.translate("MainWindow", "Fin", None, -1))
        self.pblecture.setText(QtWidgets.QApplication.translate("MainWindow", "Lecture", None, -1))
        self.pbpause.setText(QtWidgets.QApplication.translate("MainWindow", "Pause", None, -1))
        self.pbstop.setText(QtWidgets.QApplication.translate("MainWindow", "Stop", None, -1))
        self.pbsuivant.setText(QtWidgets.QApplication.translate("MainWindow", "Suivant", None, -1))
        self.pbprecedent.setText(QtWidgets.QApplication.translate("MainWindow", "Préceédent", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "LISTE DE LECTURE", None, -1))
        self.pbplus.setText(QtWidgets.QApplication.translate("MainWindow", "+", None, -1))
        self.pbmoins.setText(QtWidgets.QApplication.translate("MainWindow", "-", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Volume:", None, -1))
        self.labelVol.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))

from PySide2.QtMultimediaWidgets import QVideoWidget
